print('hello python!!')
print('what is this?')
print('**************')
print('hello python!!')
print('what is this?')
print('**************')
print('hello python!!')
print('what is this?')
print('**************')
print('hello python!!')
print('what is this?')
print('how are you?')
